version: 0.2

env:
    LOGIN: 7cf2078ee5cbdcefea96c71d3379dac3f935024e:sonartoken
    HOST: https://sonarcloud.io:HOST
    Organization: Hrishin0:Organization
    Project: Devops-Project:Project
phases:
    install:
        runtime-versions:
            python: 3.11
            
        commands:
            - apt-get update
            - apt-get install -y python3-pip jq
            - pip3 install --upgrade pip
            - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
            - export PATH=$PATH:/sonar-scanner-5.0.1.3006-linux/bin/
    pre_build:
        commands:
            - python --version
            # - pylint $CODEBUILD_SRC_DIR/*.py
            - pylint $CODEBUILD_SRC_DIR/website/*.py
            - sleep 5
            - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project > analysis.json
            - cat analysis.json
    build:
        commands:
            - sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner \
                  -Dsonar.login=${secrets-manager:LOGIN} \
                  -Dsonar.host.url=${secrets-manager:HOST} \
                  -Dsonar.projectKey=${secrets-manager:Project} \
                  -Dsonar.organization=${secrets-manager:Organization} \
                  -Dsonar.python.coverage.reportPaths=coverage.xml
            - sleep 5
            - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=${secrets-manager:Project} > result.json
            - cat result.json
            - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0; fi # Exit with error code 1 based on quality gate status
# artifacts:
#     files:
#         - '**/*'




  # secrets-manager:
  #   LOGIN: prod/hrishin:sonartoken
  #   HOST: prod/hrishin:HOST
  #   Organization: prod/hrishin:Organization
  #   Project: prod/hrishin:Project
  
          # commands:
          #   - sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
          #   - sleep 5
          #   - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
          #   - cat result.json
          #   - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi