# Generated by Django 2.1.15 on 2024-03-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_auto_20240319_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
