# Generated by Django 2.1.15 on 2024-03-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20240316_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='petimages'),
        ),
    ]
