          # commands:
          #   - sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
          #   - sleep 5
          #   - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
          #   - cat result.json
          #   - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi

    # LOGIN: 7cf2078ee5cbdcefea96c71d3379dac3f935024e
    # HOST: https://sonarcloud.io
    # Organization: Hrishin0
    # Project: Devops-Project

  #- sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -X -Dsonar.login="7cf2078ee5cbdcefea96c71d3379dac3f935024e"  -Dsonar.host.url="https://sonarcloud.io"  -Dsonar.projectKey="Devops-Project"  -Dsonar.organization="Hrishin0"
  
              